name: Publish package to GitHub Packages
on:
  release:
    types: [created]
permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8.0.452+9
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Publish package
        run: sbt test publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
